<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver requiresartwork (yes|no) "no">
			<!ATTLIST driver unofficial (yes|no) "no">
			<!ATTLIST driver nosoundhardware (yes|no) "no">
			<!ATTLIST driver incomplete (yes|no) "no">
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.243 (mame0243-276-gffab5b98fae-dirty)" debug="no" mameconfig="10">
	<machine name="1941" sourcefile="cps1.cpp">
		<description>1941: Counter Attack (World 900227)</description>
		<year>1990</year>
		<manufacturer>Capcom</manufacturer>
		<rom name="41em_30.11f" size="131072" crc="4249ec61" sha1="5323cfa6938e6d95db8469f09b2fb5b5c5068bfc" region="maincpu" offset="0" flags="1000"/>
		<rom name="41em_35.11h" size="131072" crc="ddbee5eb" sha1="0fef53398f4e2cd6ccc7bc122dd893e0a4e2e052" region="maincpu" offset="1" flags="1000"/>
		<rom name="41em_31.12f" size="131072" crc="584e88e5" sha1="af254408d939cc439b5653e60afbccdf59777085" region="maincpu" offset="40000" flags="1000"/>
		<rom name="41em_36.12h" size="131072" crc="3cfc31d0" sha1="7c0614e4e25502ff2d18aa4a97c91bf05ead875f" region="maincpu" offset="40001" flags="1000"/>
		<rom name="41-32m.8h" size="524288" crc="4e9648ca" sha1="d8e67e6e3a6dc79053e4f56cfd83431385ea7611" region="maincpu" offset="80000" flags="140"/>
		<rom name="41-5m.7a" size="524288" crc="01d1cb11" sha1="621e5377d1aaa9f7270d85bea1bdeef6721cdd05" region="gfx" offset="0" flags="6100"/>
		<rom name="41-7m.9a" size="524288" crc="aeaa3509" sha1="6124ef06d9dfdd879181856bd49853f1800c3b87" region="gfx" offset="2" flags="6100"/>
		<rom name="41-1m.3a" size="524288" crc="ff77985a" sha1="7e08df3a829bf9617470a46c79b713d4d9ebacae" region="gfx" offset="4" flags="6100"/>
		<rom name="41-3m.5a" size="524288" crc="983be58f" sha1="83a4decdd775f859240771269b8af3a5981b244c" region="gfx" offset="6" flags="6100"/>
		<rom name="41_9.12b" size="65536" crc="0f9d8527" sha1="3a00dd5772f38081fde11d8d61ba467379e2a636" region="audiocpu" offset="0" flags="0"/>
		<rom name="41_18.11c" size="131072" crc="d1f15aeb" sha1="88089383f2d54fc97026a67f067d448eee5bd0c2" region="oki" offset="0" flags="0"/>
		<rom name="41_19.12c" size="131072" crc="15aec3a6" sha1="8153c03aba005bab62bf0e8b3d15ec1c346326fd" region="oki" offset="20000" flags="0"/>
		<rom name="buf1" size="279" crc="eb122de7" sha1="b26b5bfe258e3e184f069719f9fd008d6b8f6b9b" region="aboardplds" offset="0" flags="0"/>
		<rom name="ioa1" size="279" crc="59c7ee3b" sha1="fbb887c5b4f5cb8df77cec710eaac2985bc482a6" region="aboardplds" offset="0" flags="0"/>
		<rom name="prg1" size="279" crc="f1129744" sha1="a5300f301c1a08a7da768f0773fa0fe3f683b237" region="aboardplds" offset="0" flags="0"/>
		<rom name="rom1" size="279" crc="41dc73b9" sha1="7d4c9f1693c821fbf84e32dd6ef62ddf14967845" region="aboardplds" offset="0" flags="0"/>
		<rom name="sou1" size="279" crc="84f4b2fe" sha1="dcc9e86cc36316fe42eace02d6df75d08bc8bb6d" region="aboardplds" offset="0" flags="0"/>
		<rom name="yi24b.1a" size="279" crc="3004dcdf" sha1="a73d86d1545af1d99a03d88af83449ec82b03c5c" region="bboardplds" offset="0" flags="0"/>
		<rom name="iob1.11e" size="279" crc="3abc0700" sha1="973043aa46ec6d5d1db20dc9d5937005a0f9f6ae" region="bboardplds" offset="0" flags="0"/>
		<device_ref name="m68000"/>
		<device_ref name="z80"/>
		<device_ref name="screen"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="generic_latch_8"/>
		<device_ref name="generic_latch_8"/>
		<device_ref name="ym2151"/>
		<device_ref name="okim6295"/>
		<chip type="cpu" tag="maincpu" name="Motorola MC68000" clock="10000000"/>
		<chip type="cpu" tag="audiocpu" name="Zilog Z80" clock="3579545"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="2151" name="YM2151 OPM" clock="3579545"/>
		<chip type="audio" tag="oki" name="OKI MSM6295 ADPCM" clock="1000000"/>
		<display tag="screen" type="raster" rotate="270" width="384" height="224" refresh="59.637405" pixclock="8000000" htotal="512" hbend="64" hbstart="448" vtotal="262" vbend="16" vbstart="240" />
		<sound channels="1"/>
		<input players="2" coins="2">
			<control type="joy" player="1" buttons="2" ways="8"/>
			<control type="joy" player="2" buttons="2" ways="8"/>
		</input>
		<dipswitch name="Coin A" tag="DSWA" mask="7">
			<diplocation name="SW(A)" number="1"/>
			<diplocation name="SW(A)" number="2"/>
			<diplocation name="SW(A)" number="3"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="1 Coin/1 Credit" value="7" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="6"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="4"/>
			<dipvalue name="1 Coin/6 Credits" value="3"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="56">
			<diplocation name="SW(A)" number="4"/>
			<diplocation name="SW(A)" number="5"/>
			<diplocation name="SW(A)" number="6"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="56" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="48"/>
			<dipvalue name="1 Coin/3 Credits" value="40"/>
			<dipvalue name="1 Coin/4 Credits" value="32"/>
			<dipvalue name="1 Coin/6 Credits" value="24"/>
		</dipswitch>
		<dipswitch name="2 Coins to Start, 1 to Continue" tag="DSWA" mask="64">
			<diplocation name="SW(A)" number="7"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWA" mask="128">
			<diplocation name="SW(A)" number="8"/>
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="7">
			<diplocation name="SW(B)" number="1"/>
			<diplocation name="SW(B)" number="2"/>
			<diplocation name="SW(B)" number="3"/>
			<dipvalue name="0 (Easiest)" value="7"/>
			<dipvalue name="1" value="6"/>
			<dipvalue name="2" value="5"/>
			<dipvalue name="3 (Normal)" value="4" default="yes"/>
			<dipvalue name="4" value="3"/>
			<dipvalue name="5" value="2"/>
			<dipvalue name="6" value="1"/>
			<dipvalue name="7 (Hardest)" value="0"/>
		</dipswitch>
		<dipswitch name="Level Up Timer" tag="DSWB" mask="24">
			<diplocation name="SW(B)" number="4"/>
			<diplocation name="SW(B)" number="5"/>
			<dipvalue name="More Slowly" value="24" default="yes"/>
			<dipvalue name="Slowly" value="16"/>
			<dipvalue name="Quickly" value="8"/>
			<dipvalue name="More Quickly" value="0"/>
		</dipswitch>
		<dipswitch name="Bullet's Speed" tag="DSWB" mask="96">
			<diplocation name="SW(B)" number="6"/>
			<diplocation name="SW(B)" number="7"/>
			<dipvalue name="Very Slow" value="96" default="yes"/>
			<dipvalue name="Slow" value="64"/>
			<dipvalue name="Fast" value="32"/>
			<dipvalue name="Very Fast" value="0"/>
		</dipswitch>
		<dipswitch name="Initial Vitality" tag="DSWB" mask="128">
			<diplocation name="SW(B)" number="8"/>
			<dipvalue name="3 Bars" value="128" default="yes"/>
			<dipvalue name="4 Bars" value="0"/>
		</dipswitch>
		<dipswitch name="Throttle Game Speed" tag="DSWC" mask="1">
			<diplocation name="SW(C)" number="1"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="1" default="yes"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWC" mask="2">
			<diplocation name="SW(C)" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Free Play" tag="DSWC" mask="4">
			<diplocation name="SW(C)" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Freeze" tag="DSWC" mask="8">
			<diplocation name="SW(C)" number="4"/>
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWC" mask="16">
			<diplocation name="SW(C)" number="5"/>
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWC" mask="32">
			<diplocation name="SW(C)" number="6"/>
			<dipvalue name="Off" value="32"/>
			<dipvalue name="On" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWC" mask="64">
			<diplocation name="SW(C)" number="7"/>
			<dipvalue name="No" value="64"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Game Mode" tag="DSWC" mask="128">
			<diplocation name="SW(C)" number="8"/>
			<dipvalue name="Game" value="128" default="yes"/>
			<dipvalue name="Test" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="IN0" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<port tag=":DSWA">
		</port>
		<port tag=":DSWB">
		</port>
		<port tag=":DSWC">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
	<machine name="1941j" sourcefile="cps1.cpp" cloneof="1941" romof="1941">
		<description>1941: Counter Attack (Japan)</description>
		<year>1990</year>
		<manufacturer>Capcom</manufacturer>
		<rom name="41_36.12f" size="131072" crc="7fbd42ab" sha1="4e52a599e3099bf3cccabb89152c69f216fde79e" region="maincpu" offset="0" flags="1000"/>
		<rom name="41_42.12h" size="131072" crc="c7781f89" sha1="7e99c433de0c903791ae153a3cc8632042b0a90d" region="maincpu" offset="1" flags="1000"/>
		<rom name="41_37.13f" size="131072" crc="c6464b0b" sha1="abef422d891d32334a858d49599f1ef7cf0db45d" region="maincpu" offset="40000" flags="1000"/>
		<rom name="41_43.13h" size="131072" crc="440fc0b5" sha1="e725535533c25a2c80a45a2200bbfd0dcda5ed97" region="maincpu" offset="40001" flags="1000"/>
		<rom name="41_34.10f" size="131072" crc="b5f341ec" sha1="95c740332e9e05250979a098e951600ca89cfde4" region="maincpu" offset="80000" flags="1000"/>
		<rom name="41_40.10h" size="131072" crc="3979837d" sha1="e35bca5cd6f7559447c553c7866a3934080ca018" region="maincpu" offset="80001" flags="1000"/>
		<rom name="41_35.11f" size="131072" crc="95cc979a" sha1="96a22d2accdcd1ed3829ab0e1f17c1615f8bb2a9" region="maincpu" offset="c0000" flags="1000"/>
		<rom name="41_41.11h" size="131072" crc="57496819" sha1="fe705a25a2c6523c3bc0105f4b183931c5ffcc81" region="maincpu" offset="c0001" flags="1000"/>
		<rom name="41_09.4b" size="131072" crc="be1b6bc2" sha1="0b11efb7adf6bb9c5fdef702171edd38c149e338" region="gfx" offset="0" flags="7000"/>
		<rom name="41_01.4a" size="131072" crc="d8946fc1" sha1="e18d2bd5517a9a74973f5a505e59e400db3843e2" region="gfx" offset="1" flags="7000"/>
		<rom name="41_13.9b" size="131072" crc="2e06d0ec" sha1="b7c886dce6bc5eefa34e39faec658dd9df34f82c" region="gfx" offset="2" flags="7000"/>
		<rom name="41_05.9a" size="131072" crc="d8ba28e0" sha1="dd1908166b32cf3bb3222f6d3febc21371463395" region="gfx" offset="3" flags="7000"/>
		<rom name="41_24.5e" size="131072" crc="5aa43cee" sha1="15e1aa2fee8deb25eefba067395961fee3e4c84d" region="gfx" offset="4" flags="7000"/>
		<rom name="41_17.5c" size="131072" crc="bbeff902" sha1="1bf421072387ab7d59b57ecd33cb5ae6fd8ecd06" region="gfx" offset="5" flags="7000"/>
		<rom name="41_38.8h" size="131072" crc="8889c0aa" sha1="23b74cc78fe1057c1776ea1f7371801441125a85" region="gfx" offset="6" flags="7000"/>
		<rom name="41_32.8f" size="131072" crc="f0168249" sha1="1ce2330ea4460e7e72f16a1f7edbfa8abba6b5a0" region="gfx" offset="7" flags="7000"/>
		<rom name="41_10.5b" size="131072" crc="b7eb6a6d" sha1="444b49e81cd46e90a9e1dfcf465f19c38189b2d7" region="gfx" offset="100000" flags="7000"/>
		<rom name="41_02.5a" size="131072" crc="802e8153" sha1="baf19220c53949dac0d0b75368d5f1ee6c32b619" region="gfx" offset="100001" flags="7000"/>
		<rom name="41_14.10b" size="131072" crc="5a33f676" sha1="96794463ddfae7ce4a7d7e6b65ff1b8da7b3dd74" region="gfx" offset="100002" flags="7000"/>
		<rom name="41_06.10a" size="131072" crc="4e53650b" sha1="a5b19b1ce38f04296dee38d35015869607ecc260" region="gfx" offset="100003" flags="7000"/>
		<rom name="41_25.7e" size="131072" crc="94add360" sha1="6f3542f028bdc453d0254de599b124240ea98259" region="gfx" offset="100004" flags="7000"/>
		<rom name="41_18.7c" size="131072" crc="a5e1c1f3" sha1="1961ad3c8965c51da8a19a7283333f3a19bb2030" region="gfx" offset="100005" flags="7000"/>
		<rom name="41_39.9h" size="131072" crc="5b5c3949" sha1="485b1baecee6bb9a6667baf404375fc758bdfb76" region="gfx" offset="100006" flags="7000"/>
		<rom name="41_33.9f" size="131072" crc="7a31b0e2" sha1="f2eca12f4e89266d923a94d0837c555bc1c6cb29" region="gfx" offset="100007" flags="7000"/>
		<rom name="41_23.13b" merge="41_9.12b" size="65536" crc="0f9d8527" sha1="3a00dd5772f38081fde11d8d61ba467379e2a636" region="audiocpu" offset="0" flags="0"/>
		<rom name="41_30.12c" merge="41_18.11c" size="131072" crc="d1f15aeb" sha1="88089383f2d54fc97026a67f067d448eee5bd0c2" region="oki" offset="0" flags="0"/>
		<rom name="41_31.13c" merge="41_19.12c" size="131072" crc="15aec3a6" sha1="8153c03aba005bab62bf0e8b3d15ec1c346326fd" region="oki" offset="20000" flags="0"/>
		<rom name="buf1" merge="buf1" size="279" crc="eb122de7" sha1="b26b5bfe258e3e184f069719f9fd008d6b8f6b9b" region="aboardplds" offset="0" flags="0"/>
		<rom name="ioa1" merge="ioa1" size="279" crc="59c7ee3b" sha1="fbb887c5b4f5cb8df77cec710eaac2985bc482a6" region="aboardplds" offset="0" flags="0"/>
		<rom name="prg1" merge="prg1" size="279" crc="f1129744" sha1="a5300f301c1a08a7da768f0773fa0fe3f683b237" region="aboardplds" offset="0" flags="0"/>
		<rom name="rom1" merge="rom1" size="279" crc="41dc73b9" sha1="7d4c9f1693c821fbf84e32dd6ef62ddf14967845" region="aboardplds" offset="0" flags="0"/>
		<rom name="sou1" merge="sou1" size="279" crc="84f4b2fe" sha1="dcc9e86cc36316fe42eace02d6df75d08bc8bb6d" region="aboardplds" offset="0" flags="0"/>
		<rom name="yi22b.1a" size="279" crc="b5cad2a0" sha1="3b1232cf821617bc9819fa7b9b3f4e7fc66976f3" region="bboardplds" offset="0" flags="0"/>
		<rom name="lwio.12e" size="279" crc="ad52b90c" sha1="f0fd6aeea515ee449320fe15684e6b3ab7f97bf4" region="bboardplds" offset="0" flags="0"/>
		<device_ref name="m68000"/>
		<device_ref name="z80"/>
		<device_ref name="screen"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="generic_latch_8"/>
		<device_ref name="generic_latch_8"/>
		<device_ref name="ym2151"/>
		<device_ref name="okim6295"/>
		<chip type="cpu" tag="maincpu" name="Motorola MC68000" clock="10000000"/>
		<chip type="cpu" tag="audiocpu" name="Zilog Z80" clock="3579545"/>
		<chip type="audio" tag="mono" name="Speaker"/>
		<chip type="audio" tag="2151" name="YM2151 OPM" clock="3579545"/>
		<chip type="audio" tag="oki" name="OKI MSM6295 ADPCM" clock="1000000"/>
		<display tag="screen" type="raster" rotate="270" width="384" height="224" refresh="59.637405" pixclock="8000000" htotal="512" hbend="64" hbstart="448" vtotal="262" vbend="16" vbstart="240" />
		<sound channels="1"/>
		<input players="2" coins="2">
			<control type="joy" player="1" buttons="2" ways="8"/>
			<control type="joy" player="2" buttons="2" ways="8"/>
		</input>
		<dipswitch name="Coin A" tag="DSWA" mask="7">
			<diplocation name="SW(A)" number="1"/>
			<diplocation name="SW(A)" number="2"/>
			<diplocation name="SW(A)" number="3"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="1"/>
			<dipvalue name="2 Coins/1 Credit" value="2"/>
			<dipvalue name="1 Coin/1 Credit" value="7" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="6"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="4"/>
			<dipvalue name="1 Coin/6 Credits" value="3"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="56">
			<diplocation name="SW(A)" number="4"/>
			<diplocation name="SW(A)" number="5"/>
			<diplocation name="SW(A)" number="6"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="8"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="56" default="yes"/>
			<dipvalue name="1 Coin/2 Credits" value="48"/>
			<dipvalue name="1 Coin/3 Credits" value="40"/>
			<dipvalue name="1 Coin/4 Credits" value="32"/>
			<dipvalue name="1 Coin/6 Credits" value="24"/>
		</dipswitch>
		<dipswitch name="2 Coins to Start, 1 to Continue" tag="DSWA" mask="64">
			<diplocation name="SW(A)" number="7"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWA" mask="128">
			<diplocation name="SW(A)" number="8"/>
			<dipvalue name="Off" value="128" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="7">
			<diplocation name="SW(B)" number="1"/>
			<diplocation name="SW(B)" number="2"/>
			<diplocation name="SW(B)" number="3"/>
			<dipvalue name="0 (Easiest)" value="7"/>
			<dipvalue name="1" value="6"/>
			<dipvalue name="2" value="5"/>
			<dipvalue name="3 (Normal)" value="4" default="yes"/>
			<dipvalue name="4" value="3"/>
			<dipvalue name="5" value="2"/>
			<dipvalue name="6" value="1"/>
			<dipvalue name="7 (Hardest)" value="0"/>
		</dipswitch>
		<dipswitch name="Level Up Timer" tag="DSWB" mask="24">
			<diplocation name="SW(B)" number="4"/>
			<diplocation name="SW(B)" number="5"/>
			<dipvalue name="More Slowly" value="24" default="yes"/>
			<dipvalue name="Slowly" value="16"/>
			<dipvalue name="Quickly" value="8"/>
			<dipvalue name="More Quickly" value="0"/>
		</dipswitch>
		<dipswitch name="Bullet's Speed" tag="DSWB" mask="96">
			<diplocation name="SW(B)" number="6"/>
			<diplocation name="SW(B)" number="7"/>
			<dipvalue name="Very Slow" value="96" default="yes"/>
			<dipvalue name="Slow" value="64"/>
			<dipvalue name="Fast" value="32"/>
			<dipvalue name="Very Fast" value="0"/>
		</dipswitch>
		<dipswitch name="Initial Vitality" tag="DSWB" mask="128">
			<diplocation name="SW(B)" number="8"/>
			<dipvalue name="3 Bars" value="128" default="yes"/>
			<dipvalue name="4 Bars" value="0"/>
		</dipswitch>
		<dipswitch name="Throttle Game Speed" tag="DSWC" mask="1">
			<diplocation name="SW(C)" number="1"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="1" default="yes"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWC" mask="2">
			<diplocation name="SW(C)" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Free Play" tag="DSWC" mask="4">
			<diplocation name="SW(C)" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Freeze" tag="DSWC" mask="8">
			<diplocation name="SW(C)" number="4"/>
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWC" mask="16">
			<diplocation name="SW(C)" number="5"/>
			<dipvalue name="Off" value="16" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWC" mask="32">
			<diplocation name="SW(C)" number="6"/>
			<dipvalue name="Off" value="32"/>
			<dipvalue name="On" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWC" mask="64">
			<diplocation name="SW(C)" number="7"/>
			<dipvalue name="No" value="64"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Game Mode" tag="DSWC" mask="128">
			<diplocation name="SW(C)" number="8"/>
			<dipvalue name="Game" value="128" default="yes"/>
			<dipvalue name="Test" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="IN0" mask="64">
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<port tag=":DSWA">
		</port>
		<port tag=":DSWB">
		</port>
		<port tag=":DSWC">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
	<machine name="1941r1" sourcefile="cps1.cpp" cloneof="1941" romof="1941">
		<description>1941: Counter Attack (World)</description>
		<year>1990</year>
		<manufacturer>Capcom</manufacturer>
		<rom name="41e_30.11f" size="131072" crc="9deb1e75" sha1="68d9f91bef6a5c9e1bcbf286629aed6b37b4acb9" region="maincpu" offset="0" flags="1000"/>
		<rom name="41e_35.11h" size="131072" crc="d63942b3" sha1="b4bc7d06dcefbc075d316f2d31abbd4c7a99dbae" region="maincpu" offset="1" flags="1000"/>
		<rom name="41e_31.12f" size="131072" crc="df201112" sha1="d84f63bffeb9255cbabc02f23d7511f9b3c6a96c" region="maincpu" offset="40000" flags="1000"/>
		<rom name="41e_36.12h" size="131072" crc="816a818f" sha1="3e491a30352b71ddd775142f3a80cdde480b669f" region="maincpu" offset="40001" flags="1000"/>
		<rom name="41-32m.8h" merge="41-32m.8h" size="524288" crc="4e9648ca" sha1="d8e67e6e3a6dc79053e4f56cfd83431385ea7611" region="maincpu" offset="80000" flags="140"/>
		<rom name="41-5m.7a" merge="41-5m.7a" size="524288" crc="01d1cb11" sha1="621e5377d1aaa9f7270d85bea1bdeef6721cdd05" region="gfx" offset="0" flags="6100"/>
		<rom name="41-7m.9a" merge="41-7m.9a" size="524288" crc="aeaa3509" sha1="6124ef06d9dfdd879181856bd49853f1800c3b87" region="gfx" offset="2" flags="6100"/>
		<rom name="41-1m.3a" merge="41-1m.3a" size="524288" crc="ff77985a" sha1="7e08df3a829bf9617470a46c79b713d4d9ebacae" region="gfx" offset="4" flags="6100"/>
		<rom name="41-3m.5a" merge="41-3m.5a" size="524288" crc="983be58f" sha1="83a4decdd775f859240771269b8af3a5981b244c" region="gfx" offset="6" flags="6100"/>
		<rom name="41_9.12b" merge="41_9.12b" size="65536" crc="0f9d8527" sha1="3a00dd5772f38081fde11d8d61ba467379e2a636" region="audiocpu" offset="0" flags="0"/>
		<rom name="41_18.11c" merge="41_18.11c" size="131072" crc="d1f15aeb" sha1="88089383f2d54fc97026a67f067d448eee5bd0c2" region="oki" offset="0" flags="0"/>
		<rom name="41_19.12c" merge="41_19.12c" size="131072" crc="15aec3a6" sha1="8153c03aba005bab62bf0e8b3d15ec1c346326fd" region="oki" offset="20000" flags="0"/>
		<rom name="buf1" merge="buf1" size="279" crc="eb122de7" sha1="b26b5bfe258e3e184f069719f9fd008d6b8f6b9b" region="aboardplds" offset="0" flags="0"/>
		<rom name="ioa1" merge="ioa1" size="279" crc="59c7ee3b" sha1="fbb887c5b4f5cb8df77cec710eaac2985bc482a6" region="aboardplds" offset="0" flags="0"/>
		<rom name="prg1" merge="prg1" size="279" crc="f1129744" sha1="a5300f301c1a08a7da768f0773fa0fe3f683b237" region="aboardplds" offset="0" flags="0"/>
		<rom name="rom1" merge="rom1" size="279" crc="41dc73b9" sha1="7d4c9f1693c821fbf84e32dd6ef62ddf14967845" region="aboardplds" offset="0" flags="0"/>